language: node
node_js: 12
script: parcel build www/index.html
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  fqdn: fiszki.odel.ga
  github_token: $GITHUB_TOKEN
  on:
    branch: master
